apiVersion: apps/v1
kind: Deployment
metadata:
  name: sport-matchmaking-match-service
spec:
  selector:
    matchLabels:
      app: sport-matchmaking-match-service
  template:
    metadata:
      labels:
        app: sport-matchmaking-match-service
    spec:
      containers:
      - name: sport-matchmaking-match-service
        image: sport-matchmaking-match-service:latest
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 100m
            memory: "16Mi"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: user
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: password
          - name: PGHOST
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: host
          - name: PGPORT
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: port
          - name: PGDATABASE
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: database
