apiVersion: v1
kind: Secret
metadata:
  name: match-service-keycloak-credentials
type: Opaque
data:
  url: aHR0cDovL2tleWNsb2FrOjgwODA= # http://keycloak:8080
  realm: c3BvcnQtbWF0Y2htYWtpbmc= # sport-matchmaking
  clientId: bWF0Y2gtc2VydmljZQ== # match-service