apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sport-matchmaking-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
    limits:
      storage: 1Gi
  storageClassName: standard